service: crami-uruguay-emergencia-serverless

provider:
    name: aws
    runtime: nodejs20.x
    stage: dev
    region: us-east-1
    environment:
        PG_USER: ${env:PG_USER}
        PG_PASSWORD: ${env:PG_PASSWORD}
        PG_HOST: ${env:PG_HOST}
        PG_PORT: ${env:PG_PORT}
        PG_DATABASE: ${env:PG_DATABASE}

functions:
    # USERS
    login:
        handler: src/handlers/users.UserSignup
        timeout: 30
        events:
            - http:
                  path: api/users/signUp
                  method: post

plugins:
    - serverless-offline
    - serverless-dotenv-plugin

custom:
    serverless-offline:
        host: localhost
        httpPort: 3000
package:
    individually: true
